version: '3.4'

services:
  DataRequester:
    image: data-requester
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 main.py "]
    ports:
      - 5678:5678
    environment:
      - CITY=Wrocław
      - USER=student
      - PASS=sys-wbud
      #- IP=46.101.199.108
      - IP=broker.emqx.io
