version: '3.4'

services:
  codespacesprojecttemplatepy:
    image: codespacesprojecttemplatepy
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CITY=Wrocław
      - USER=student
      - PASS=sys-wbud
      - IP=46.101.108.102
